### ISSUE TITLE
Doesn't work with inline-block or floats?

### ISSUE THREAD

**Issue by drawingfrommemory** [julianlloyd/scrollReveal.js#134]
Correct me if I'm wrong, but this doesn't seem to work with `display: inline-block` or floated elements, does it? I can't get it to work on my own site and if I add `display :inline-block` to your `.block` class in the demo everything disappears.

**Comment by julianlloyd** [comment]
Hi @drawingfrommemory 

This is the `.block` class from the Scroll Reveal demo.
```CSS
.block {
  border-radius: 5px;
  margin-bottom: 150%;
}
```
If you add `display: inline-block` to the `.block` class in Scroll Reveal demo, everything disappears because those elements don’t actually have any content. However, an easy way to fix this is to define a width. (And for the sake of it, let’s add `float: left` too.)
```CSS
.block {
  border-radius: 5px;
  margin-bottom: 150%;
  display: inline-block;
  width: 48px;
  float: left;
}
```
Everything will still work as expected.

Beyond this, I cannot help you as you haven’t actually given any details about your situation.
It’s most helpful if you demonstrate (eg. with [JS Bin](http://jsbin.com) or [Codepen](http://codepen.io)) what you’re trying to achieve, or a bug you’ve recreated. (Don’t forget to mention if you’re working with WordPress or other platforms/plug-ins.)
